import React from "react";

export const RiskTabContent = React.memo(() => {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-foreground">Risk Disclosure</h2>

      <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
        <p className="font-semibold text-foreground">
          IMPORTANT: Please read this Risk Disclosure carefully before using the PillarX Algorithmic
          Insights service.
        </p>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">High Risk Warning</h3>
          <p>
            Trading digital assets, cryptocurrencies, and their derivatives involves a high degree
            of risk and may not be suitable for all investors. The high degree of leverage often
            obtainable in digital asset trading can work against you as well as for you. You may
            sustain a total loss of the funds you deposit with your broker, and you may incur losses
            beyond these amounts.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">
            No Guarantee of Profits or Performance
          </h3>
          <p>
            Past performance is not indicative of future results. No representation is being made
            that any account will or is likely to achieve profits or losses similar to those shown
            in historical data. The events provided by PillarX Algorithmic Insights are based on
            algorithmic analysis and do not guarantee profitable outcomes.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">Market Volatility</h3>
          <p>
            Digital asset markets are highly volatile and can experience rapid price fluctuations.
            Market conditions can change quickly, and events may become outdated or inaccurate
            before you can act on them. External factors such as regulatory changes, technological
            developments, and macroeconomic events can significantly impact asset prices.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">Algorithmic Limitations</h3>
          <p>
            The events provided by this service are generated by algorithms that analyze historical
            and real-time data. However, algorithms cannot predict all market conditions or
            unforeseen events. Technical errors, data inaccuracies, or system failures may affect
            the quality and timeliness of events.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">Independent Decision-Making</h3>
          <p>
            You are solely responsible for making your own trading decisions. The events provided
            by this service are for informational purposes only and should not be considered as
            personalized investment advice. You should conduct your own research and consult with a
            qualified financial advisor before making any trading decisions.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">Risk of Loss</h3>
          <p>
            You should only trade with capital that you can afford to lose. Digital asset trading is
            not suitable for individuals who cannot afford to bear the risk of substantial losses.
            Before deciding to trade, you should carefully consider your investment objectives, level
            of experience, and risk tolerance.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">Regulatory Considerations</h3>
          <p>
            Digital asset regulations vary by jurisdiction and are subject to change. You are
            responsible for ensuring that your trading activities comply with all applicable laws and
            regulations in your jurisdiction. PillarX does not provide legal or regulatory advice.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-base font-semibold text-foreground">No Liability</h3>
          <p>
            PillarX and its affiliates shall not be liable for any losses, damages, or claims
            arising from your use of the service or reliance on the events provided. By using this
            service, you acknowledge and accept all risks associated with digital asset trading.
          </p>
        </section>

        <p className="font-semibold text-foreground pt-4">
          By clicking "Continue" and accepting the consent agreement, you acknowledge that you have
          read, understood, and accepted this Risk Disclosure in its entirety.
        </p>
      </div>
    </div>
  );
});

RiskTabContent.displayName = "RiskTabContent";
