// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta as any)?.env?.VITE_SUPABASE_URL || "https://odhxqhkulhsbjaslwroq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any)?.env?.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kaHhxaGt1bGhzYmphc2x3cm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Mjc0NDAsImV4cCI6MjA3NzQwMzQ0MH0.V5Rn4e_KQolIKeSi70-w1k_JBMN5HB9yzrefmy0yxzU";

// Import the supabase client like this:
// import { supabase } from "../../integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});