export const PHONE_OTP_AUTH_KEY = 'PILLARX_PHONE_OTP_AUTHENTICATED';
export const PHONE_OTP_PHONE_NUMBER_KEY = 'PILLARX_PHONE_OTP_NUMBER';
export const PHONE_OTP_COUNTRY_OPTION_LABEL_KEY =
  'PILLARX_PHONE_OTP_COUNTRY_OPTION_LABEL';
export const PHONE_OTP_VERIFICATION_SID_KEY =
  'PILLARX_PHONE_OTP_VERIFICATION_SID';

// Legacy key that previously stored raw private keys in localStorage.
// Kept for migration only.
export const PHONE_OTP_PRIVATE_KEY = 'PILLARX_LOCAL_PRIVATE_KEY';
export const PHONE_OTP_ENCRYPTED_VAULT_KEY =
  'PILLARX_LOCAL_PRIVATE_KEY_ENCRYPTED_V1';
export const PHONE_OTP_UNLOCKED_SESSION_KEY =
  'PILLARX_LOCAL_PRIVATE_KEY_UNLOCKED_SESSION_V1';
export const PHONE_OTP_AUTH_STATE_EVENT = 'pillarx:phone-otp-auth-state-change';
