const axios = require('axios');
const fs = require('fs');
const path = require('path');

const OUTPUT_FILE = path.resolve(__dirname, '../src/apps/perps/constants/tokenLogos.ts');
const HYPERLIQUID_API = 'https://api.hyperliquid.xyz/info';
// User provided Premium API
const MOBULA_API = 'https://premium-api.mobula.io/api/2/fast-search';

// Ensure output dir exists
const dir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
}

async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function getAllAssets() {
    console.log('Fetching asset list from Hyperliquid...');
    try {
        const response = await axios.post(HYPERLIQUID_API, { type: 'meta' });
        // response.data.universe is array of { name: 'ETH', ... }
        return response.data.universe.map(u => u.name);
    } catch (e) {
        console.error('Failed to fetch assets:', e.message);
        return [];
    }
}

async function getMobulaLogo(symbol) {
    let searchSymbol = symbol;
    if (symbol.startsWith('k') && symbol.length > 2 && symbol !== 'kBENJI') {
        searchSymbol = symbol.slice(1);
    }
    if (symbol === 'HYPE') searchSymbol = 'HYPE';

    try {
        const url = `${MOBULA_API}?mode=trendings&sortBy=volume_24h&input=${searchSymbol}`;
        const response = await axios.get(url);
        if (response.data && response.data.data && response.data.data.length > 0) {
            return response.data.data[0].logo || null;
        }
        return null;
    } catch (e) {
        if (e.response && e.response.status === 429) {
            console.warn(`[${symbol}] Rate Limited (429)`);
            return 'RATE_LIMIT';
        }
        console.warn(`[${symbol}] Failed to fetch logo: ${e.message}`);
        return null;
    }
}

function loadExistingLogos() {
    if (fs.existsSync(OUTPUT_FILE)) {
        try {
            const content = fs.readFileSync(OUTPUT_FILE, 'utf8');
            const jsonStart = content.indexOf('{');
            const jsonEnd = content.lastIndexOf('}');
            if (jsonStart !== -1 && jsonEnd !== -1) {
                const jsonStr = content.substring(jsonStart, jsonEnd + 1);
                return JSON.parse(jsonStr);
            }
        } catch (e) {
            console.warn('Could not parse existing logo file, starting fresh.');
        }
    }
    return {};
}

function saveLogos(logoMap) {
    const fileContent = `// Auto-generated by scripts/generateTokenLogos.js
export const TOKEN_LOGOS: Record<string, string> = ${JSON.stringify(logoMap, null, 2)};
`;
    fs.writeFileSync(OUTPUT_FILE, fileContent);
}

async function main() {
    const assets = await getAllAssets();
    console.log(`Found ${assets.length} assets.`);

    // Load existing
    const logoMap = loadExistingLogos();
    const doneCount = Object.keys(logoMap).length;
    console.log(`Loaded ${doneCount} existing logos.`);

    // Filter out already done
    const todoAssets = assets.filter(a => !logoMap[a]);
    console.log(`Remaining to fetch: ${todoAssets.length}`);

    // Batch processing
    const BATCH_SIZE = 2; // Be conservative even with premium

    for (let i = 0; i < todoAssets.length; i += BATCH_SIZE) {
        const batch = todoAssets.slice(i, i + BATCH_SIZE);
        console.log(`Processing batch ${i + 1}/${todoAssets.length} ...`);

        const promises = batch.map(async (symbol) => {
            const logo = await getMobulaLogo(symbol);
            if (logo === 'RATE_LIMIT') {
                // Should stop or retry? For now, just mark failing.
                // Actually if we hit rate limit, we should ideally pause. 
                // But let's see if Premium avoids it.
                return;
            }
            if (logo) {
                console.log(`✅ ${symbol} -> ${logo.slice(0, 30)}...`);
                logoMap[symbol] = logo;
            } else {
                console.log(`❌ ${symbol} not found`);
                // Mark as not found so we don't retry forever? 
                // Alternatively, don't add to map, so next run retries. 
                // Let's NOT add to map if not found, to allow retry.
            }
            await sleep(Math.random() * 200);
        });

        await Promise.all(promises);

        // Save progress occasionally
        saveLogos(logoMap);

        // Sleep between batches
        await sleep(500);
    }

    saveLogos(logoMap);
    console.log(`\n🎉 Done! Saved ${Object.keys(logoMap).length} logos to ${OUTPUT_FILE}`);
}

main();
